DROP TABLE IF EXISTS users_albums;

DROP TABLE IF EXISTS tracks;

DROP TABLE IF EXISTS albums;

DROP TABLE IF EXISTS labels;

DROP TABLE IF EXISTS formats;

DROP TABLE IF EXISTS artists;

DROP TABLE IF EXISTS users;